title = "videah's blog"
description = "seemed like a good idea at the time"
author = "videah"

# The URL the site will be built for
base_url = "https://blog.videah.net"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# When set to "true", the HTML output files will be minified
minify_html = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Generates info for RSS readers
generate_feeds = true

theme = "sigmund"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
author = "videah"
github_account = "videah"
bluesky_account = "videah.net"
mastodon_url = "https://meow.social/@videah"
umami_domain = "analytics.videah.net"
umami_id = "69c46ed5-0fa1-49fd-946a-a63718e5dc2c"
umami_track_domain = "blog.videah.net"
generate_jpeg_xl = false